experimental-features = nix-command flakes
build-users-group =
sandbox = true
sandbox-fallback = false
require-drop-supplementary-groups = false
max-jobs = auto
ssl-cert-file = /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
