[config]

[templates]

[templates.vesktop-flatpak]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/discord-midnight.css"
output_path = "~/.var/app/dev.vencord.Vesktop/config/vesktop/themes/noctalia.theme.css"

[templates.adwsteamgtk-flatpak]
input_path = "~/.config/noctalia/templates/adwsteamgtk.css"
output_path = "~/.var/app/io.github.Foldex.AdwSteamGtk/config/AdwSteamGtk/custom.css"

[templates.zed-native]
input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/zed.json"
output_path = "~/.config/zed/themes/noctalia.json"

[templates.sddm]
input_path = "/usr/share/sddm/themes/noctalia/theme.template.conf"
output_path = "/var/lib/nocblue/sddm/theme.conf"
